<a href="https://colab.research.google.com/github/LokeshPanuganti15/DAA/blob/main/DAY_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [12]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from mlxtend.frequent_patterns import apriori, association_rules

In [6]:
titanic = pd.read_csv("/content/Titanic.csv")
titanic.head()

  Class Gender    Age Survived
0   3rd   Male  Child       No
1   3rd   Male  Child       No
2   3rd   Male  Child       No
3   3rd   Male  Child       No
4   3rd   Male  Child       No

In [7]:
titanic.tail()

     Class  Gender    Age Survived
2196  Crew  Female  Adult      Yes
2197  Crew  Female  Adult      Yes
2198  Crew  Female  Adult      Yes
2199  Crew  Female  Adult      Yes
2200  Crew  Female  Adult      Yes

In [9]:
titanic.describe()

       Class Gender    Age Survived
count   2201   2201   2201     2201
unique     4      2      2        2
top     Crew   Male  Adult       No
freq     885   1731   2092     1490

In [11]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2201 entries, 0 to 2200
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Class     2201 non-null   object
 1   Gender    2201 non-null   object
 2   Age       2201 non-null   object
 3   Survived  2201 non-null   object
dtypes: object(4)
memory usage: 68.9+ KB

In [14]:
titanic.duplicated()

0       False
1        True
2        True
3        True
4        True
        ...
2196     True
2197     True
2198     True
2199     True
2200     True
Length: 2201, dtype: bool

In [16]:
titanic.isnull().sum()

Class       0
Gender      0
Age         0
Survived    0
dtype: int64

In [19]:
titanic['Class'].unique()

array(['3rd', '1st', '2nd', 'Crew'], dtype=object)

In [22]:
titanic['Class'].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [23]:
titanic['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [24]:
titanic['Gender'].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [25]:
titanic['Age'].unique()

array(['Child', 'Adult'], dtype=object)

In [27]:
titanic['Survived'].unique()

array(['No', 'Yes'], dtype=object)

In [30]:
df=pd.get_dummies(titanic,dtype='int')
df.head()

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,0,0,1,0,0,1,0,1,1,0
1,0,0,1,0,0,1,0,1,1,0
2,0,0,1,0,0,1,0,1,1,0
3,0,0,1,0,0,1,0,1,1,0
4,0,0,1,0,0,1,0,1,1,0

In [32]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Class_1st, Age_Adult)
10  0.118582                             (Class_2nd, Age_Adult)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Class_3rd, Survived_No)
14  0.391640                          (Class_Crew, Gender_Male)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Class_Crew, Survived_No)
17  0.193094                         (Gender_Female, Age_Adult)
18  0.156293                      (Gender_Female, Survived_Yes)
19  0.757383                           (Age_Adult, Gender_Male)
20  0.619718                         (Gender_Male, Survived_No)
21  0.166742                        (Survived_Yes, Gender_Male)
22  0.653339                           (Age_Adult, Survived_No)
23  0.297138                          (Survived_Yes, Age_Adult)
24  0.209905                (Class_3rd, Age_Adult, Gender_Male)
25  0.191731              (Gender_Male, Class_3rd, Survived_No)
26  0.216265                (Class_3rd, Age_Adult, Survived_No)
27  0.391640               (Class_Crew, Age_Adult, Gender_Male)
28  0.304407             (Gender_Male, Class_Crew, Survived_No)
29  0.305770               (Class_Crew, Age_Adult, Survived_No)
30  0.143571           (Gender_Female, Survived_Yes, Age_Adult)
31  0.603816              (Gender_Male, Age_Adult, Survived_No)
32  0.153567             (Age_Adult, Survived_Yes, Gender_Male)
33  0.175829   (Gender_Male, Class_3rd, Age_Adult, Survived_No)
34  0.304407  (Gender_Male, Class_Crew, Age_Adult, Survived_No)